name: Deploy Flask to Azure
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'miappazuredemo-norma'  
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}